spring:
  application.name: RecipeFinder
  servlet.multipart:
    max-file-size: 100MB
    max-request-size: 100MB
  data.redis:
    host: localhost
    port: 6379
    username:
    password:
  profiles:
    active: ollama
server.tomcat.max-swallow-size: -1

logging.pattern.dateformat: yyyy-MM-dd HH:mm:ss.SSS

app:
  available-ingredients-in-fridge: bacon,onions

---
spring.config.activate.on-profile: ollama
langchain4j.ollama:
  chat-model:
    base-url: http://localhost:11434
    model-name: llama3.2
    temperature: 0.5
  embedding-model:
    base-url: ${langchain4j.ollama.chat-model.base-url}
    model-name: llama3.2
