spring:
  application.name: RecipeFinder
  servlet.multipart:
    max-file-size: 100MB
    max-request-size: 100MB
  profiles:
    active: ollama
server.tomcat.max-swallow-size: -1

logging.pattern.dateformat: yyyy-MM-dd HH:mm:ss.SSS

app:
  available-ingredients-in-fridge: bacon,onions

langchain4j:
  community.redis:
    enabled: true
    host: 127.0.0.1
    port: 6379
  rag.retrieval:
    max-results: 2
    min-score: 0.7
---
spring.config.activate.on-profile: ollama
langchain4j.ollama:
  chat-model:
    base-url: http://127.0.0.1:11434
    model-name: llama3.2
    temperature: 0.5
  embedding-model:
    base-url: ${langchain4j.ollama.chat-model.base-url}
    model-name: llama3.2

